post:
  tags:
    - Training
  summary: Initiate annotator training (async)
  description: Start training the tool's annotation model
  operationId: trainAnnotator
  requestBody:
    content:
      application/json:
        schema:
  responses:
    '201':
      description: Training initialized
      content:
        application/json:
          schema:
      links:
        GetTrainingStatus:
          operationId: annotatorTrainingStatus
    '404':
      $ref: ../components/responses/NotFound.yaml
    '500':
      $ref: ../components/responses/InternalServerError.yaml
